apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    run: nginx
  name: nginx-rs
spec:
  replcas: 2
  selector:
    matchLabels:
      run: nginx
    template:
      metadata:
        labels:
          run: nginx
      spec:
        containers:
        - image: nginx:1.14.2
          name: nginx
