##
# Base system roles
##

# Update and upgrade packages
- src: oefenweb.apt
  version: v2.4.9

# Install utils
- src: weareinteractive.apt
  version: 2.12.0

# Create users and add them to sudo group
- src: singleplatform-eng.users
  version: v1.2.6

# Allow users sudo without password
- src: weareinteractive.sudo
  version: 1.14.1

# SSH hardening
- src: willshersystems.sshd
  version: v0.13.0

# Sysctl configure
- src: linuxhq.sysctl
  version: v0.0.9

# Journald configure
- src: 0x0i.journald
  version: v0.2.0

# Install node-expoter for Prometheus moniitoring
- src: cloudalchemy.node_exporter
  version: 2.0.0

# Create proxmox CT and VM
- src: udelarinterior.proxmox_create_lxc
  version: v2.2.0

# Create one morere proxmox CT and VM 
- src: bellackn.proxmox_lxc
  version: 4.1.0

# Install pip (foor creating LXC via ansible)
- src: geerlingguy.pip
  version: 2.1.0

# Configure UFW firewall
- src: weareinteractive.ufw
  version: 2.0.1

# Configure SSH for Digital Ocean special
- src: diodonfrost.ssh_hardening
  version: 1.1.0

# Nginx exporter role for prometheus monitoring
- src: bdellegrazie.nginx_exporter
  version: v3.2.0
  
# Nginx exporter role for prometheus monitoring
- src: bdellegrazie.ansible-role-prometheus_exporter
  version: v2.0.3

# Nginx role
- src: jdauphant.nginx
  version: v2.21.2

# certs
- src: dudefellah.certbot
  version: 0.2.0

# Wireguard role
- src: raylas.wireguard
  version: 0.2.6

# Mongodb role
- src: undergreen.mongodb
  version: v2.7.0
  
# Mongodb_exporter role
- src: kostiantyn-nemchenko.mongodb_exporter
  version: 2.0.0

# Bind_exporter role
- src: cloudalchemy.bind_exporter

# Docker role
- src: geerlingguy.docker
  version: 4.1.0

# Set timezone
- src: oefenweb.timezone
  version: v1.0.47
